USE [master]
GO

/****** Object:  Database [LojaDB]    Script Date: 30/04/2024 22:10:04 ******/
CREATE DATABASE [LojaDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Loja', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Loja.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Loja_log', FILENAME = N'F:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\Loja_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LojaDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LojaDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LojaDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LojaDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LojaDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LojaDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [LojaDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LojaDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LojaDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LojaDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LojaDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LojaDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LojaDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LojaDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LojaDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LojaDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LojaDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LojaDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LojaDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LojaDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LojaDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LojaDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LojaDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LojaDB] SET RECOVERY FULL 
GO

ALTER DATABASE [LojaDB] SET  MULTI_USER 
GO

ALTER DATABASE [LojaDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LojaDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LojaDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LojaDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LojaDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LojaDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [LojaDB] SET QUERY_STORE = ON
GO

ALTER DATABASE [LojaDB] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [LojaDB] SET  READ_WRITE 
GO


USE [LojaDB]
GO

/****** Object:  User [loja]    Script Date: 30/04/2024 22:10:52 ******/
CREATE USER [loja] FOR LOGIN [loja] WITH DEFAULT_SCHEMA=[dbo]
GO

USE [LojaDB]
GO

CREATE SEQUENCE PessoaIdSeq
    START WITH 1
    INCREMENT BY 1;


USE [LojaDB]
GO

/****** Object:  Table [dbo].[Usuario]    Script Date: 30/04/2024 22:16:29 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Usuario](
	[id_Usuario] [int] IDENTITY(1,1) NOT NULL,
	[login] [varchar](50) NULL,
	[senha] [varchar](50) NULL,
	[email] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_Usuario] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [LojaDB]
GO

/****** Object:  Table [dbo].[Pessoa_Fisica]    Script Date: 30/04/2024 22:18:03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Pessoa_Fisica](
	[id_PessoaFisica] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](100) NULL,
	[logradouro] [varchar](255) NULL,
	[cidade] [varchar](100) NULL,
	[estado] [varchar](50) NULL,
	[telefone] [varchar](20) NULL,
	[email] [varchar](100) NULL,
	[cpf] [varchar](11) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_PessoaFisica] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [LojaDB]
GO

/****** Object:  Table [dbo].[Pessoa_Juridica]    Script Date: 30/04/2024 22:20:16 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Pessoa_Juridica](
	[id_PessoaJuridica] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](100) NULL,
	[logradouro] [varchar](255) NULL,
	[cidade] [varchar](100) NULL,
	[estado] [varchar](50) NULL,
	[telefone] [varchar](20) NULL,
	[email] [varchar](100) NULL,
	[cnpj] [varchar](14) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_PessoaJuridica] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO



USE [LojaDB]
GO

/****** Object:  Table [dbo].[Produto]    Script Date: 30/04/2024 22:21:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Produto](
	[id_Produto] [int] IDENTITY(1,1) NOT NULL,
	[nome] [varchar](100) NULL,
	[quantidade] [int] NULL,
	[precoVenda] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_Produto] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


USE [LojaDB]
GO

/****** Object:  Table [dbo].[Movimento_Compra]    Script Date: 30/04/2024 22:22:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Movimento_Compra](
	[id_MovimentoCompra] [int] IDENTITY(1,1) NOT NULL,
	[id_Usuario] [int] NULL,
	[id_Produto] [int] NULL,
	[id_PessoaJuridica] [int] NULL,
	[quantidade] [int] NULL,
	[preco_Unitario] [decimal](10, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[id_MovimentoCompra] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Movimento_Compra]  WITH CHECK ADD FOREIGN KEY([id_PessoaJuridica])
REFERENCES [dbo].[Pessoa_Juridica] ([id_PessoaJuridica])
GO

ALTER TABLE [dbo].[Movimento_Compra]  WITH CHECK ADD FOREIGN KEY([id_Produto])
REFERENCES [dbo].[Produto] ([id_Produto])
GO

ALTER TABLE [dbo].[Movimento_Compra]  WITH CHECK ADD FOREIGN KEY([id_Usuario])
REFERENCES [dbo].[Usuario] ([id_Usuario])
GO


USE [LojaDB]
GO

/****** Object:  Table [dbo].[Movimento_Venda]    Script Date: 30/04/2024 22:22:19 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Movimento_Venda](
	[id_MovimentoVenda] [int] IDENTITY(1,1) NOT NULL,
	[id_Usuario] [int] NULL,
	[id_Produto] [int] NULL,
	[id_PessoaFisica] [int] NULL,
	[quantidade] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[id_MovimentoVenda] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Movimento_Venda]  WITH CHECK ADD FOREIGN KEY([id_PessoaFisica])
REFERENCES [dbo].[Pessoa_Fisica] ([id_PessoaFisica])
GO

ALTER TABLE [dbo].[Movimento_Venda]  WITH CHECK ADD FOREIGN KEY([id_Produto])
REFERENCES [dbo].[Produto] ([id_Produto])
GO

ALTER TABLE [dbo].[Movimento_Venda]  WITH CHECK ADD FOREIGN KEY([id_Usuario])
REFERENCES [dbo].[Usuario] ([id_Usuario])
GO


